version: "3.6"

services:
  app:
    environment:
      ENV: "prod"
      EXEC_TEST: "1"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.labels.web == true]

networks:
  dmz_network:
    driver: overlay
