version: "3.6"

services:
  app:
    build:
      context: ./build
      dockerfile: app/dockerfile
    image: ${COMPOSE_PROJECT_NAME}_app
    networks:
      - dmz_network


networks:
  dmz_network:
